### ISSUE TITLE
Pblio crashes when using the cache

### ISSUE THREAD

**Issue by lpabon** [pblcache/pblcache#42]
```
[lpabon@localhost pblio]$ ls -al
total 121800
drwxrwxr-x 5 lpabon lpabon     4096 May  6 17:09 .
drwxrwxr-x 4 lpabon lpabon       34 Mar 10 15:39 ..
-rw-r--r-- 1 lpabon lpabon 10485760 May  6 17:11 cache
-rw-r--r-- 1 lpabon lpabon 47185920 May  6 17:11 file1
-rw-r--r-- 1 lpabon lpabon 47185920 May  6 17:11 file2
-rw-r--r-- 1 lpabon lpabon 10489856 May  6 17:11 file3

[lpabon@localhost pblio]$ ./pblio -asu1=./file1 -asu2=./file2 -asu3=./file3 -cache=./cache 2>&1 | head -30
-----
pblio
-----
Cache   : ./cache (New)
C Size  : 0.01 GB
ASU1    : 0.04 GB
ASU2    : 0.04 GB
ASU3    : 0.01 GB
BSUs    : 50
Contexts: 1
Run time: 300 s
-----
panic: REQUIRE:
	func (github.com/pblcache/pblcache/cache.SubBlockBuffer) 0x47e659
	File /home/lpabon/git/golang/src/github.com/pblcache/pblcache/cache/utils.go:24

goroutine 571 [running]:
github.com/lpabon/godbc.dbc_panic(0x5903b0, 0x7, 0x0, 0x0, 0x0, 0x0)
	/home/lpabon/git/golang/src/github.com/lpabon/godbc/godbc.go:85 +0x58c
github.com/lpabon/godbc.Require(0xc20cb61e00, 0x0, 0x0, 0x0)
	/home/lpabon/git/golang/src/github.com/lpabon/godbc/godbc.go:100 +0x5b
github.com/pblcache/pblcache/cache.SubBlockBuffer(0xc20bfc3000, 0x1000, 0x3f000, 0x100001000, 0x1, 0x0, 0x0, 0x0)
	/home/lpabon/git/golang/src/github.com/pblcache/pblcache/cache/utils.go:24 +0x79
github.com/pblcache/pblcache/cache.(*CacheMap).Put(0xc20803c660, 0xc20cc2a800, 0x0, 0x0)
	/home/lpabon/git/golang/src/github.com/pblcache/pblcache/cache/cachemap.go:118 +0x200
github.com/pblcache/pblcache/apps/pblio/spc.readandstore(0x7f98462c6f38, 0xc20803c810, 0xc20803c660, 0x1, 0x124e000, 0x3, 0xc20bfc3000, 0x1000, 0x3f000, 0xc20cc14d20)
	/home/lpabon/git/golang/src/github.com/pblcache/pblcache/apps/pblio/spc/cacheio.go:42 +0x16b
created by github.com/pblcache/pblcache/apps/pblio/spc.read
	/home/lpabon/git/golang/src/github.com/pblcache/pblcache/apps/pblio/spc/cacheio.go:118 +0x762
```

**Comment by lpabon** [comment]
Found in 0125ebea91191294b51240f45687aa0696b5e847
